### ISSUE TITLE
TF transformation error and coordinate system conversion frequency

### ISSUE THREAD

**Issue by HomieRegina** [LORD-MicroStrain/ROS-MSCL#249] opened 2023-05-25 17:17 UTC
Hi! Thanks for your great work! I use gx5-25. When I run the newest driver, the terminal will report an error as shown in the following figure. 
![图片](https://github.com/LORD-MicroStrain/microstrain_inertial/assets/107244263/4c0efd8d-a3d1-4994-89b7-7f288cd7545c)
Then I tried to check the tf-tree. At this point, my IMU data publishing frequency is set to 100Hz, but the coordinate system conversion is far from reaching 100Hz. As shown in the following figure. 
![图片](https://github.com/LORD-MicroStrain/microstrain_inertial/assets/107244263/4a032434-35ef-4360-a26b-ee8dc555242a)
Has anyone ever encountered this problem? How to solve this problem? 
Looking forward to a reply. Thank you!

**Comment by robbiefish** [comment] 2024-03-25 20:41
This appears to be a duplicate of #248, which should be fixed in `4.0.0`.

Feel free to reopen if this is still an issue

**Closed as completed by robbiefish** 2024-03-25 20:41 UTC
Labels: bug, New
